sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: wasd10086
  alioss:
    access-key-id: LTAI5tSAxQcoDiagVLsjjmBF
    access-key-secret: I7GRDmkhcZbpTIy5TjJdhaaRpvSuKR
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucket-name: the-fifth-season
